Repository Kid-Topia/KidsTopia, pull requests merged in 2024-05, with the labels that each got.

#11 [#5] Feat: Bottom Navigation View 생성
  app/build.gradle.kts
  app/src/main/java/com/limheejin/kidstopia/presentation/activity/MainActivity.kt
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_user.xml
  app/src/main/res/drawable/nav_color.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/menu/mnu_nav.xml
Labels: Development

#13 [#4] Feat: Search Api 연결, Detail Fragment에 videoID 전달(Bundle), 예외 처리 등 기능 구현
  app/src/main/java/com/limheejin/kidstopia/presentation/activity/MainActivity.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/adapter/RVSearchAdapter.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/fragment/SearchFragment.kt
  app/src/main/res/drawable/bg_fragment_search.xml
  app/src/main/res/drawable/bg_rv_searchitem.xml
  app/src/main/res/drawable/bg_search.xml
  app/src/main/res/drawable/ic_kidstopia.xml
  app/src/main/res/drawable/preview_search_item.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/rv_searchfragment_item.xml
Labels: Development

#18 [#17, #14] Fix: API 키 변경, 뷰모델 코드 위치 수정
  app/src/main/java/com/limheejin/kidstopia/presentation/activity/MainActivity.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/fragment/SearchFragment.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/network/NetworkClient.kt
  app/src/main/java/com/limheejin/kidstopia/viewmodel/SearchViewModel.kt
  app/src/main/res/layout/activity_main.xml
Labels: bug, Development

#19 [#14] Feat: SearchViewModel 수정 및 MVVM 구현, 검색기능 상황별로 코드 구현
  app/src/main/java/com/limheejin/kidstopia/presentation/activity/MainActivity.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/fragment/SearchFragment.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/network/SearchInterface.kt
  app/src/main/java/com/limheejin/kidstopia/viewmodel/SearchViewModel.kt
  app/src/main/res/layout/fragment_search.xml
Labels: Development, enhancement

#21 [#3] Feat: 모든 기능 구현
  app/src/main/java/com/limheejin/kidstopia/model/database/MyFavoriteVideoDatabase.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/activity/MainActivity.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/fragment/SearchFragment.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/fragment/VideoDetailFragment.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/network/NetworkClient.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/network/VideoInterface.kt
  app/src/main/res/anim/none.xml
  app/src/main/res/anim/slide_down.xml
  app/src/main/res/anim/slide_up.xml
  app/src/main/res/drawable/bg_detailfragment_grd.xml
  app/src/main/res/drawable/bg_detailfragment_img.png
  app/src/main/res/drawable/btn_detailfragment_like.xml
  app/src/main/res/drawable/btn_detailfragment_like_slc.xml
  app/src/main/res/drawable/btn_detailfragment_play.png
  app/src/main/res/drawable/slc_btn_like.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_video_detail.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: Development, Design

#26 [#25] Fix:수정 VideoDetailFragment 기능
  app/src/main/java/com/limheejin/kidstopia/presentation/fragment/VideoDetailFragment.kt
Labels: bug

#31 [#6] Feat: HomeFragment 인기 동영상 리사이클러뷰, API 이용하여 값 할당
  app/src/main/java/com/limheejin/kidstopia/presentation/adapter/CategoryAdapter.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/adapter/ChannelAdapter.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/adapter/MostPopularRVAdapter.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/fragment/HomeFragment.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/fragment/MostAdapter.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/network/VideoInterface.kt
Labels: Development

#36 [#35] Refactor: 전체적인 코드 수정
  app/src/main/java/com/limheejin/kidstopia/presentation/fragment/VideoDetailFragment.kt
  app/src/main/res/drawable/btn_detailfragment_play_slc.png
  app/src/main/res/drawable/slc_btn_play.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_video_detail.xml
Labels: Development, Design

#45 [#38] UI: 전체적인 UI 디테일 수정
  app/src/main/java/com/limheejin/kidstopia/model/SearchData.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/adapter/MostPopularRVAdapter.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/network/NetworkClient.kt
  app/src/main/res/drawable/bg_fragment_home.xml
  app/src/main/res/drawable/bg_fragment_myvideo.xml
  app/src/main/res/drawable/ic_kidstopia_img.png
  app/src/main/res/drawable/ic_kidstopia_title.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/category_item.xml
  app/src/main/res/layout/channel_item.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_video.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_video_detail.xml
  app/src/main/res/layout/most_popular_item.xml
  app/src/main/res/layout/rv_favorite_video.xml
  app/src/main/res/layout/rv_visited_video.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: Design

#46 Fix: replace -> add 로 수정, onDestroy popBackStack 설정
  app/src/main/java/com/limheejin/kidstopia/presentation/fragment/HomeFragment.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/fragment/MyVideoFragment.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/fragment/SearchFragment.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/fragment/VideoDetailFragment.kt
Labels: bug

#47 [#37] 클린코드 구조 패키징 네이밍
  app/src/main/java/com/limheejin/kidstopia/model/ChannelData.kt
  app/src/main/java/com/limheejin/kidstopia/model/SearchData.kt
  app/src/main/java/com/limheejin/kidstopia/model/database/ChannelData.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/activity/MainActivity.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/adapter/CategoryAdapter.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/adapter/ChannelAdapter.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/adapter/MostPopularVideoAdapter.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/adapter/MyFavoriteVideoAdapter.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/adapter/RVSearchAdapter.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/fragment/HomeFragment.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/fragment/MyVideoFragment.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/fragment/SearchFragment.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/fragment/VideoDetailFragment.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/network/CategoryInterface.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/network/ChannelInterface.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/network/NetworkClient.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/network/VideoInterface.kt
  app/src/main/java/com/limheejin/kidstopia/repository/NetworkRepository.kt
  app/src/main/java/com/limheejin/kidstopia/repository/NetworkRepositoryImpl.kt
  app/src/main/java/com/limheejin/kidstopia/repository/Repository.kt
  app/src/main/java/com/limheejin/kidstopia/repository/RoomRepository.kt
  app/src/main/java/com/limheejin/kidstopia/repository/RoomRepositoryImpl.kt
  app/src/main/java/com/limheejin/kidstopia/viewmodel/MyVideoViewModel.kt
  app/src/main/java/com/limheejin/kidstopia/viewmodel/SearchViewModel.kt
  app/src/main/java/com/limheejin/kidstopia/viewmodel/VideoDetailViewModel.kt
  app/src/main/res/drawable/btn_detailfragment_back.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_video_detail.xml
  app/src/main/res/values/strings.xml
Labels: bug, Development

#54 Feat: 전체 코드 리팩토링, XML 네이밍, DecimalFormat 추가 및 적용
  app/build.gradle.kts
  app/src/main/java/com/limheejin/kidstopia/model/DecimalFormat.kt
  app/src/main/java/com/limheejin/kidstopia/model/PopularData.kt
  app/src/main/java/com/limheejin/kidstopia/model/SearchData.kt
  app/src/main/java/com/limheejin/kidstopia/model/database/MyFavoriteVideoDatabase.kt
  app/src/main/java/com/limheejin/kidstopia/model/database/MyFavoriteVideoEntity.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/CloseDialog.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/activity/MainActivity.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/adapter/CategoryAdapter.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/adapter/MostPopularVideoAdapter.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/adapter/MyFavoriteVideoAdapter.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/adapter/RVSearchAdapter.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/adapter/VisitedPageAdapter.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/fragment/HomeFragment.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/fragment/MyVideoFragment.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/fragment/SearchFragment.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/fragment/VideoDetailFragment.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/network/CategoryInterface.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/network/NetworkClient.kt
  app/src/main/java/com/limheejin/kidstopia/presentation/network/SearchInterface.kt
  app/src/main/java/com/limheejin/kidstopia/repository/NetworkRepository.kt
  app/src/main/java/com/limheejin/kidstopia/repository/NetworkRepositoryImpl.kt
  app/src/main/java/com/limheejin/kidstopia/repository/RoomRepository.kt
  app/src/main/java/com/limheejin/kidstopia/repository/RoomRepositoryImpl.kt
  app/src/main/java/com/limheejin/kidstopia/viewmodel/HomeViewModel.kt
  app/src/main/java/com/limheejin/kidstopia/viewmodel/MyVideoViewModel.kt
  app/src/main/java/com/limheejin/kidstopia/viewmodel/SearchViewModel.kt
  app/src/main/java/com/limheejin/kidstopia/viewmodel/VideoDetailViewModel.kt
  app/src/main/res/drawable/bg_btn_dialog_cancel.xml
  app/src/main/res/drawable/bg_btn_dialog_confirm.xml
  app/src/main/res/drawable/bg_fragment_detail_grd.xml
  app/src/main/res/drawable/bg_fragment_detail_img.png
  app/src/main/res/drawable/bg_fragment_myvideo_circleprofile.xml
  app/src/main/res/drawable/bg_iv_searchbox.xml
  app/src/main/res/drawable/bg_spinner_item.xml
  app/src/main/res/drawable/btn_fragment_detail_back.xml
  app/src/main/res/drawable/btn_fragment_detail_like.xml
  app/src/main/res/drawable/btn_fragment_detail_like_slc.xml
  app/src/main/res/drawable/btn_fragment_detail_play.png
  app/src/main/res/drawable/btn_fragment_detail_play_slc.png
  app/src/main/res/drawable/preview_search_item.png
  app/src/main/res/drawable/slc_fragment_detail_like.xml
  app/src/main/res/drawable/slc_fragment_detail_play.xml
  app/src/main/res/font/pretendardbold.otf
  app/src/main/res/font/pretendardmedium.otf
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/category_item.xml
  app/src/main/res/layout/channel_item.xml
  app/src/main/res/layout/dialog.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_video.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_video_detail.xml
  app/src/main/res/layout/most_popular_item.xml
  app/src/main/res/layout/rv_favorite_video.xml
  app/src/main/res/layout/rv_searchfragment_item.xml
  app/src/main/res/layout/rv_visited_video.xml
  app/src/main/res/layout/spinner_dropdown_item.xml
  app/src/main/res/menu/mnu_nav.xml
  app/src/main/res/values/themes.xml
Labels: Development, enhancement

#59 [#57] Feat: DataStore로 사용자 수정 구현, MyVideoFragment 수정, 다이얼로그 수정 등
  app/build.gradle.kts
  app/src/main/java/com/kidstopia/kidstopia/model/UserPreferences.kt
  app/src/main/java/com/kidstopia/kidstopia/presentation/activity/MainActivity.kt
  app/src/main/java/com/kidstopia/kidstopia/presentation/fragment/HomeFragment.kt
  app/src/main/java/com/kidstopia/kidstopia/presentation/fragment/MyVideoFragment.kt
  app/src/main/res/drawable/ic_editpencil.png
  app/src/main/res/layout/dialog_exit.xml
  app/src/main/res/layout/dialog_username.xml
  app/src/main/res/layout/fragment_my_video.xml
Labels: Development, enhancement

#63 [#39] Fix: Spinner, ScrollView, 네비게이션바 디테일 겹침 오류 해결
  app/src/main/java/com/kidstopia/kidstopia/presentation/activity/MainActivity.kt
  app/src/main/java/com/kidstopia/kidstopia/presentation/fragment/HomeFragment.kt
  app/src/main/java/com/kidstopia/kidstopia/presentation/network/NetworkClient.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_video.xml
  app/src/main/res/layout/fragment_video_detail.xml
  app/src/main/res/layout/spinner_item.xml
  app/src/main/res/values/themes.xml
Labels: bug

#64 Fix: MyVideo 재밌게 본 영상 바로 반영되도록 수정
  app/src/main/java/com/kidstopia/kidstopia/model/UserPreferences.kt
  app/src/main/java/com/kidstopia/kidstopia/presentation/activity/MainActivity.kt
  app/src/main/res/layout/fragment_my_video.xml
Labels: bug

#65 Fix: 다이얼로그 버튼 통일 및 마이비디오 영상 제목 표출
  app/src/main/java/com/kidstopia/kidstopia/presentation/adapter/VisitedPageAdapter.kt
  app/src/main/java/com/kidstopia/kidstopia/presentation/fragment/MyVideoFragment.kt
  app/src/main/res/drawable/bg_btn_dialog_cancel.xml
  app/src/main/res/layout/dialog_exit.xml
  app/src/main/res/layout/dialog_username.xml
  app/src/main/res/layout/rv_visited_video.xml
Labels: Development, Design

#69 Update README.md
  README.md
Labels: documentation, enhancement
